export const LOCALITIES = [
  "HUDA Sector 2",
  "New Colony",
  "New Colony Extension",
  "Adarsh Colony",
  "Krishna Colony",
  "Kalra Colony",
  "Shiv Colony",
  "Shiva Puri (Shivapuri)",
  "Kailash Nagar",
  "Camp Colony",
  "Housing Board Colony",
  "Jawahar Nagar",
  "Prakash Vihar Colony",
  "Panchwati Colony",
  "Ramnagar",
  "Deepak Colony",
  "Shyam Nagar Colony",
  "Alapur",
  "Omaxe City",
  "SRS Prime Floor (Sector 6)",
  "RPS Urbania (Sector 10)",
  "Baghola",
  "Patli Khurd",
  "Main Market (Agra Chowk)",
  "Gol Market",
  "Railway Road",
  "Bus Stand Area",
  "Subzi Mandi Area",
  "Mathura Road Area",
  "Minar Gate",
];

export const CITIES = [
  "Palwal",
  "Faridabad",
  "Hathin",
  "Hodal",
  "Jewar",
  "Sohna",
  "Prithla",
  "Other",
];

export const ATTRIBUTE_SCHEMAS = {
  flat: {
    bhk: { label: "BHK", type: "integer", required: true },
    floor_no: { label: "Floor Number", type: "integer", required: true },
    total_floors: { label: "Total Floors", type: "integer", required: true },
    carpet_sqft: { label: "Carpet Area", type: "number", unit: "sqft" },
    superbuiltup_sqft: {
      label: "Super Built-up Area",
      type: "number",
      unit: "sqft",
    },
    furnishing: {
      label: "Furnishing",
      type: "string",
      enum: ["unfurnished", "semi_furnished", "fully_furnished"],
    },
    has_lift: { label: "Lift Available", type: "boolean" },
    has_parking: { label: "Parking Available", type: "boolean" },
    age_years: { label: "Property Age (years)", type: "integer" },
    facing: {
      label: "Facing",
      type: "string",
      enum: [
        "north",
        "south",
        "east",
        "west",
        "north_east",
        "north_west",
        "south_east",
        "south_west",
      ],
    },
    bathrooms: { label: "Bathrooms", type: "integer" },
    balconies: { label: "Balconies", type: "integer" },
    society_name: { label: "Society / Project Name", type: "string" },
    is_ddjay: {
      label: "DDJAY Scheme",
      type: "boolean",
      haryana_specific: true,
    },
    registry_status: {
      label: "Registry Status",
      type: "string",
      enum: ["registered", "unregistered", "under_process"],
      haryana_specific: true,
    },
  },
  house: {
    bhk: { label: "BHK", type: "integer", required: true },
    floors: { label: "Number of Floors", type: "integer" },
    facing: {
      label: "Facing",
      type: "string",
      enum: [
        "north",
        "south",
        "east",
        "west",
        "north_east",
        "north_west",
        "south_east",
        "south_west",
      ],
    },
    bathrooms: { label: "Bathrooms", type: "integer" },
    has_parking: { label: "Parking Available", type: "boolean" },
    furnishing: {
      label: "Furnishing",
      type: "string",
      enum: ["unfurnished", "semi_furnished", "fully_furnished"],
    },
    age_years: { label: "Property Age (years)", type: "integer" },
    registry_status: {
      label: "Registry Status",
      type: "string",
      enum: ["registered", "unregistered", "under_process"],
      haryana_specific: true,
    },
    is_lal_dora: {
      label: "Lal Dora Property",
      type: "boolean",
      haryana_specific: true,
    },
  },
  plot: {
    facing: {
      label: "Facing",
      type: "string",
      enum: [
        "north",
        "south",
        "east",
        "west",
        "north_east",
        "north_west",
        "south_east",
        "south_west",
      ],
    },
    is_corner_plot: { label: "Corner Plot", type: "boolean" },
    has_boundary_wall: { label: "Boundary Wall", type: "boolean" },
    is_gated: { label: "Gated Colony", type: "boolean" },
    road_width_ft: { label: "Road Width (ft)", type: "number", unit: "ft" },
    plot_number: { label: "Plot Number", type: "string" },
    sector_block: { label: "Sector / Block", type: "string" },
    is_lal_dora: {
      label: "Lal Dora Property",
      type: "boolean",
      haryana_specific: true,
    },
    is_ddjay: {
      label: "DDJAY Scheme",
      type: "boolean",
      haryana_specific: true,
    },
    registry_status: {
      label: "Registry Status",
      type: "string",
      enum: ["registered", "unregistered", "under_process"],
      haryana_specific: true,
    },
    is_approved: {
      label: "DTCP / HRERA Approved",
      type: "boolean",
      haryana_specific: true,
    },
    approving_authority: {
      label: "Approved By",
      type: "string",
      enum: ["DTCP", "HRERA", "MC", "DGTCP", "Other"],
    },
    registry_remarks: { label: "Registry Remarks", type: "string" },
  },
  agricultural: {
    land_type: {
      label: "Land Type",
      type: "string",
      enum: ["farm", "orchard", "pond", "mixed"],
    },
    soil_type: { label: "Soil Type", type: "string" },
    water_source: {
      label: "Water Source",
      type: "string",
      enum: ["tubewell", "canal", "rain", "none"],
    },
    current_crop: { label: "Current Crop", type: "string" },
    dist_highway_km: {
      label: "Distance from Highway (km)",
      type: "number",
      unit: "km",
      haryana_specific: true,
    },
    dist_city_km: {
      label: "Distance from City (km)",
      type: "number",
      unit: "km",
    },
    is_collector_rate_area: {
      label: "Collector Rate Area",
      type: "boolean",
      haryana_specific: true,
    },
    khasra_number: { label: "Khasra Number", type: "string" },
  },
  commercial: {
    sub_type: {
      label: "Commercial Type",
      type: "string",
      required: true,
      enum: [
        "shop",
        "office",
        "showroom",
        "warehouse",
        "industrial",
        "hotel",
        "restaurant",
      ],
    },
    floor_no: { label: "Floor Number", type: "integer" },
    total_floors: { label: "Total Floors", type: "integer" },
    power_load_kw: { label: "Power Load (KW)", type: "number", unit: "KW" },
    has_washroom: { label: "Washroom Available", type: "boolean" },
    frontage_width_ft: {
      label: "Frontage Width (ft)",
      type: "number",
      unit: "ft",
    },
    has_parking: { label: "Parking Available", type: "boolean" },
    registry_status: {
      label: "Registry Status",
      type: "string",
      enum: ["registered", "unregistered", "under_process"],
      haryana_specific: true,
    },
  },
  farmhouse: {
    total_area_acre: {
      label: "Total Area (acres)",
      type: "number",
      unit: "acre",
    },
    builtup_sqft: {
      label: "Built-up Area (sqft)",
      type: "number",
      unit: "sqft",
    },
    num_rooms: { label: "Number of Rooms", type: "integer" },
    water_source: {
      label: "Water Source",
      type: "string",
      enum: ["tubewell", "canal", "municipal", "none"],
    },
    has_orchard: { label: "Orchard / Garden", type: "boolean" },
    dist_city_km: {
      label: "Distance from City (km)",
      type: "number",
      unit: "km",
    },
    dist_highway_km: {
      label: "Distance from Highway (km)",
      type: "number",
      unit: "km",
      haryana_specific: true,
    },
  },
  villa: {
    plot_sqyard: {
      label: "Plot Area (sq yard)",
      type: "number",
      unit: "sqyard",
      required: true,
    },
    builtup_sqft: {
      label: "Built-up Area (sqft)",
      type: "number",
      unit: "sqft",
    },
    floors: { label: "Number of Floors", type: "integer" },
    bhk: { label: "BHK", type: "integer", required: true },
    has_parking: { label: "Parking Available", type: "boolean" },
    has_garden: { label: "Garden / Lawn", type: "boolean" },
    age_years: { label: "Property Age (years)", type: "integer" },
    facing: {
      label: "Facing",
      type: "string",
      enum: [
        "north",
        "south",
        "east",
        "west",
        "north_east",
        "north_west",
        "south_east",
        "south_west",
      ],
    },
    registry_status: {
      label: "Registry Status",
      type: "string",
      enum: ["registered", "unregistered", "under_process"],
      haryana_specific: true,
    },
  },
  independent_house: {
    plot_sqyard: {
      label: "Plot Area (sq yard)",
      type: "number",
      unit: "sqyard",
      required: true,
    },
    builtup_sqft: {
      label: "Built-up Area (sqft)",
      type: "number",
      unit: "sqft",
    },
    floors: { label: "Number of Floors", type: "integer" },
    bhk: { label: "BHK", type: "integer", required: true },
    has_parking: { label: "Parking Available", type: "boolean" },
    has_garden: { label: "Garden / Lawn", type: "boolean" },
    age_years: { label: "Property Age (years)", type: "integer" },
    facing: {
      label: "Facing",
      type: "string",
      enum: [
        "north",
        "south",
        "east",
        "west",
        "north_east",
        "north_west",
        "south_east",
        "south_west",
      ],
    },
    registry_status: {
      label: "Registry Status",
      type: "string",
      enum: ["registered", "unregistered", "under_process"],
      haryana_specific: true,
    },
    is_lal_dora: {
      label: "Lal Dora Property",
      type: "boolean",
      haryana_specific: true,
    },
  },
  pg: {
    pg_for: {
      label: "PG For",
      type: "string",
      required: true,
      enum: ["male", "female", "any"],
    },
    sharing_type: {
      label: "Sharing Type",
      type: "string",
      enum: ["single", "double", "triple", "dormitory"],
    },
    meals_included: { label: "Meals Included", type: "boolean" },
    attached_bathroom: { label: "Attached Bathroom", type: "boolean" },
    ac: { label: "AC Available", type: "boolean" },
  },
  warehouse: {
    height_ft: { label: "Height (ft)", type: "number", unit: "ft" },
    loading_docks: { label: "Loading Docks", type: "integer" },
    power_kva: { label: "Power (KVA)", type: "number", unit: "KVA" },
    floor_strength: { label: "Floor Strength", type: "string" },
  },
  shop: {
    floor_no: { label: "Floor Number", type: "integer" },
    frontage_width_ft: {
      label: "Frontage Width (ft)",
      type: "number",
      unit: "ft",
    },
    registry_status: {
      label: "Registry Status",
      type: "string",
      enum: ["registered", "unregistered", "under_process"],
      haryana_specific: true,
    },
  },
  office: {
    floor_no: { label: "Floor Number", type: "integer" },
    total_floors: { label: "Total Floors", type: "integer" },
    cabins: { label: "Number of Cabins", type: "integer" },
    furnishing: {
      label: "Furnishing",
      type: "string",
      enum: ["unfurnished", "semi_furnished", "fully_furnished"],
    },
    registry_status: {
      label: "Registry Status",
      type: "string",
      enum: ["registered", "unregistered", "under_process"],
      haryana_specific: true,
    },
  },
};
